spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comments
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
 
      